name: dfamedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2  
  flutter_svg: ^2.2.1 
  intl: ^0.20.2
  http: ^1.5.0
  provider: ^6.1.5+1
  vector_graphics: ^1.1.19
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  # Firebase dependencies
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  
  # Offline dependencies
  sqflite: ^2.4.2
  connectivity_plus: ^7.0.0
  path: ^1.9.1
  
  # WebSocket dependency
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  
  fonts:
    - family: Stolzl
      fonts:
        - asset: assets/fonts/stolzl_regular.otf
          weight: 400
        - asset: assets/fonts/stolzl_medium.otf
          weight: 500
  
  assets:
    - assets/svg/
